<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'ResponsiveImage\Controller\ResponsiveImageController' => __DIR__ . '/src/ResponsiveImage/Controller/ResponsiveImageController.php',
  'ResponsiveImage\Module'                               => __DIR__ . '/src/ResponsiveImage/Module.php',
  'ResponsiveImage\PhpThumb'                             => __DIR__ . '/src/ResponsiveImage/PhpThumb.php',
  'ResponsiveImage\Service\AbstractService'              => __DIR__ . '/src/ResponsiveImage/Service/AbstractService.php',
  'ResponsiveImage\Service\ConfigService'                => __DIR__ . '/src/ResponsiveImage/Service/ConfigService.php',
  'ResponsiveImage\Service\ConvertService'               => __DIR__ . '/src/ResponsiveImage/Service/ConvertService.php',
  'ResponsiveImage\Service\RecipeService'                => __DIR__ . '/src/ResponsiveImage/Service/RecipeService.php',
);
